name: Run Every Minute

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-every-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Print timestamp
        run: echo "Running at $(date -u)"
