name: Create Release PR

on:
  push:
    branches:
      - release-*

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Draft PR to main
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          gh pr create \
            --base main \
            --head "$BRANCH_NAME" \
            --title "Release: $BRANCH_NAME" \
            --body "This is an automated release PR for **$BRANCH_NAME** , and this PR is raised via a voice command" \
            --label release \
            --draft
