name: Create Release PR

on:
  push:
    branches:
      - release-*

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Draft PR to main
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "bot-${{ github.actor }}"
          git config user.email "bot-${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          # Get current branch name
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          # Fetch the latest main branch for comparison
          git fetch origin main

          # Check if a PR is already open for this branch
          if gh pr list --base main --head "$BRANCH_NAME" --state open | grep -q .; then
            echo "PR already exists for branch $BRANCH_NAME. Exiting."
            exit 0
          fi

          # Check if there are any changes against main
          if git diff --quiet origin/main...HEAD; then
            echo "No changes found against main. Exiting."
            exit 0
          fi

          # Use the latest commit message for PR title and body
          TITLE=$(git log -1 --pretty=%s)
          BODY=$(git log -1 --pretty=%b)

          gh pr create \
            --base main \
            --head "$BRANCH_NAME" \
            --title "$TITLE" \
            --body "$BODY" \
            --label release \
            --draft
